Repository mt-mods/pipeworks, pull requests merged in 2024-01, with the labels that each got.

#101 code and registrations cleanup
  .github/workflows/luacheck.yml
  common.lua
  crafts.lua
  init.lua
  materials.lua
  tubes/embedded_tube.lua
  tubes/lua.lua
  tubes/pane_embedded_tube.lua
  tubes/registration.lua
  tubes/routing.lua
  tubes/signal.lua
  tubes/sorting.lua
  tubes/teleport.lua
  tubes/vacuum.lua
Labels: cleanup

#74 Autocrafter groups support
  .editorconfig
  autocrafter.lua
  changelog.txt
Labels: enhancement

#102 Tube repair fixes
  tubes/routing.lua
  tubes/vacuum.lua
Labels: bugfix

#105 export `pipeworks.tptube.remove_tube`
  tubes/teleport.lua
Labels: enhancement
